project:
  type: website
  output-dir: docs

website:
  title: "WaterholeDetection_UN-Handbook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - S2_download_GEE.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



