project:
  type: website
  output-dir: docs

website:
  title: "Waterhole Detection - UN Handbook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Getting Started
      - href: S2_download_GEE.ipynb
        text: Download GEE Data

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



